#!/usr/bin/env python3

"""
    lldppoed

    pop poe data to database periodically
"""


try:
    import os
    import subprocess
    import sys
    import json
    import time

    from sonic_py_common import daemon_base
    from swsscommon import swsscommon
    from swsscommon.swsscommon  import ConfigDBConnector
except ImportError as err:
    raise ImportError("%s - required module not found" % str(err))

VERSION = "1.0"

SYSLOG_IDENTIFIER = "lldppoed"
PORT_INIT_TIMEOUT = 300
FAILED_CMD_TIMEOUT = 6
RETRY_LIMIT = 5


class LldpPoe(daemon_base.DaemonBase):
    REDIS_TIMEOUT_MS = 0

    def __init__(self, log_identifier):
        super(LldpPoe, self).__init__(log_identifier)

        # Open a handle to the State database
        self.state_db = swsscommon.DBConnector("STATE_DB",
                                              self.REDIS_TIMEOUT_MS,
                                              False)

        self.pending_cmds = {}

        self.state_poe_table = swsscommon.Table(self.state_db, "LLDPPOE")
        self.state_port_table = swsscommon.Table(self.state_db, swsscommon.STATE_PORT_TABLE_NAME)
        self.intf_set = set(self.state_port_table.getKeys())

    def get_lldp_neighbor_data(self):
        """
        get the lldp neighbor data
        """
        try:
            result = subprocess.run(['lldpcli', '-f', 'json', 'show',
                                        'ne', 'de'], capture_output=True, text=True, check=True)
            return result.stdout
        except subprocess.CalledProcessError as e:
            self.log_error("Error running get_lldp_neighbor_data command:", e)
            return None

    def advertise_power_to_pd(self, intf, req_power, adv_power):
        """
        set lldp pd advertise power
        """
        try:
            config_db = ConfigDBConnector()
            config_db.connect()
            poe_dict = config_db.get_table('POE')

            lldpcli_cmd = ["lldpcli", "configure", "ports", intf, "dot3", "power", "pse", "supported", "enabled", "powerpairs", "signal", "class", "class-4", "type", "2", "source", "primary", "priority", poe_dict[intf]['priority'], "requested", req_power, "allocated", adv_power]
            result = subprocess.run(lldpcli_cmd, capture_output=True, text=True, check=True)
            return
        except subprocess.CalledProcessError as e:
            self.log_error("Error running get_lldp_neighbor_data command:", e)
            return None

    def process_output_and_save_to_db(self, json_data):
        config_db = ConfigDBConnector()
        config_db.connect()
        poe_dict = config_db.get_table('POE')
        if poe_dict == dict(): #no this table
            return

        lldp_data = json.loads(json_data)
        lldp_intfs = lldp_data['lldp']['interface']
        pre_intf_set = set(self.state_poe_table.getKeys())
        lldp_intf_set = set()
        lldp_mdi_dict = {}
        lldp_med_dict = {}

        for interface in lldp_intfs:
            for intf in interface:
                if 'power' in interface[intf]['port']:
                    if intf in self.intf_set and poe_dict[intf]['lldp'] == 'enable':
                        lldp_intf_set.add(intf)
                        lldp_mdi_dict[intf] = interface[intf]['port']['power']
                elif 'lldp-med' in interface[intf]:
                    if 'poe' in interface[intf]['lldp-med']:
                        if intf in self.intf_set and poe_dict[intf]['lldp'] == 'enable':
                            lldp_intf_set.add(intf)
                            lldp_med_dict[intf] = interface[intf]['lldp-med']['poe']

        remove_set = pre_intf_set - lldp_intf_set
        add_set = lldp_intf_set - pre_intf_set
        update_set = pre_intf_set - remove_set

        for intf in remove_set:
            self.state_poe_table.delete(intf)

        for intf in add_set:
                if intf in lldp_med_dict:
                    fvs = swsscommon.FieldValuePairs([
                        ('device-type', lldp_med_dict[intf]['device-type']),
                        ('device-protocol', 'MED'),
                        ('advertised', '0'),
                        ('allocated', '0'),
                        ('requested', lldp_med_dict[intf]['power'])
                    ])
                if intf in lldp_mdi_dict:
                    fvs = swsscommon.FieldValuePairs([
                        ('device-type', lldp_mdi_dict[intf]['device-type']),
                        ('device-protocol', 'MDI'),
                        ('advertised', '0'),
                        ('allocated', '0'),
                        ('requested', lldp_mdi_dict[intf]['requested'] if 'requested' in lldp_mdi_dict[intf] else '0')
                    ])
                self.state_poe_table.set(intf, fvs)

        for intf in update_set:
                if intf in lldp_med_dict:
                    lldp_device_type = lldp_med_dict[intf]['device-type']
                    lldp_req_power = lldp_med_dict[intf]['power']
                    rc, db_device_type = self.state_poe_table.hget(intf, 'device-type')
                    rc, db_req_power = self.state_poe_table.hget(intf, 'requested')

                    if lldp_device_type != db_device_type:
                        self.state_poe_table.hset(intf, 'device-type', lldp_device_type)

                    if lldp_req_power != db_req_power:
                        self.state_poe_table.hset(intf, 'requested', lldp_req_power)

                if intf in lldp_mdi_dict:
                    lldp_device_type = lldp_mdi_dict[intf]['device-type']
                    lldp_req_power = lldp_mdi_dict[intf]['requested'] if 'requested' in lldp_mdi_dict[intf] else '0'
                    rc, db_device_type = self.state_poe_table.hget(intf, 'device-type')
                    rc, db_req_power = self.state_poe_table.hget(intf, 'requested')
                    rc, db_alloc_power = self.state_poe_table.hget(intf, 'allocated')
                    rc, db_power_adv = self.state_poe_table.hget(intf, 'advertised')

                    if lldp_device_type != db_device_type:
                        self.state_poe_table.hset(intf, 'device-type', lldp_device_type)

                    if lldp_req_power != db_req_power:
                        self.state_poe_table.hset(intf, 'requested', lldp_req_power)

                    if db_power_adv != '1' and db_alloc_power != '0':
                        self.advertise_power_to_pd(intf, db_req_power, db_alloc_power)
                        self.state_poe_table.hset(intf, 'advertised', '1')

    def run(self):
        self.log_info("Starting up...")

        if not os.geteuid() == 0:
            self.log_error("Must be root to run this daemon")
            print("Error: Must be root to run this daemon")
            sys.exit(1)

        # Set timeout to 30 seconds
        TIMEOUT = 30

        while True:
            time.sleep(TIMEOUT)
            output = self.get_lldp_neighbor_data()
            self.process_output_and_save_to_db(output)

# ============================= Functions =============================


def main():
    # Instantiate a lldppoe object
    lldppoe = LldpPoe(SYSLOG_IDENTIFIER)

    # Log all messages from INFO level and higher
    lldppoe.set_min_log_priority_info()

    lldppoe.run()

if __name__ == "__main__":
    main()
