{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version

RUN apt-get update      && \
    apt-get install -f -y  \
        libdbus-1-3        \
        libdaemon0         \
        libusb-1.0-0       \
		python3-dev

{% if docker_poe_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_poe_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_poe_debs.split(' ')) }}
{%- endif %}

{% if docker_poe_whls.strip() -%}
# Copy locally-built Python wheel dependencies
{{ copy_files("python-wheels/", docker_poe_whls.split(' '), "/python-wheels/") }}

# Install locally-built Python wheel dependencies
{{ install_python_wheels(docker_poe_whls.split(' ')) }}
{% endif %}

# Clean up
RUN apt-get clean -y            && \
    apt-get autoclean -y        && \
    apt-get autoremove -y       && \
    rm -rf /debs                   \
           /python-wheels          \
           ~/.cache


COPY ["start.sh", "/usr/bin/"]
COPY ["poeinit", "/usr/bin/"]
COPY ["poeallocp", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

ENTRYPOINT ["/usr/local/bin/supervisord"]
