# Docker image for POE

DOCKER_POE_STEM = docker-poe
DOCKER_POE = $(DOCKER_POE_STEM).gz
DOCKER_POE_DBG = $(DOCKER_POE_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_POE)_PATH = $(DOCKERS_PATH)/$(DOCKER_POE_STEM)

$(DOCKER_POE)_DEPENDS += $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(DOCKER_POE)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_POE)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG)
$(DOCKER_POE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_POE)_PYTHON_WHEELS += $(SONIC_PLATFORM_COMMON_PY3)
$(DOCKER_POE)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3)
$(DOCKER_POE)_PYTHON_WHEELS += $(SONIC_CONFIG_ENGINE_PY3)
$(DOCKER_POE)_PYTHON_WHEELS += $(SONIC_PLATFORM_API_PY3)

$(DOCKER_POE)_VERSION = 1.0.0
$(DOCKER_POE)_PACKAGE_NAME = poe

SONIC_DOCKER_IMAGES += $(DOCKER_POE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_POE)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_POE_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_POE_DBG)

$(DOCKER_POE)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_POE)_CONTAINER_NAME = poe
$(DOCKER_POE)_RUN_OPT += --privileged -t
$(DOCKER_POE)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_POE)_RUN_OPT += -v /host/warmboot:/var/warmboot
